name: WordPress Coding Standards

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        php: [ 7.4, 8.0, 8.1 ]
        
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup proper PHP version
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --no-interaction --ignore-platform-reqs --prefer-dist --no-progress

    - name: Run PHP Code Sniffer
      run: composer run-script coding-standards:check
